<?php

namespace ContainerXdVkzEv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I5s54SXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I5s54SX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I5s54SX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProductsController::ShowOneShirt' => ['privates', '.service_locator.2muTD6G', 'get_ServiceLocator_2muTD6GService', true],
            'App\\Controller\\ProductsController::albumEdit' => ['privates', '.service_locator.EmSfoSR', 'get_ServiceLocator_EmSfoSRService', true],
            'App\\Controller\\ProductsController::shirtEdit' => ['privates', '.service_locator.2muTD6G', 'get_ServiceLocator_2muTD6GService', true],
            'App\\Controller\\ProductsController::showOneAlbum' => ['privates', '.service_locator.EmSfoSR', 'get_ServiceLocator_EmSfoSRService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\ProductsController:ShowOneShirt' => ['privates', '.service_locator.2muTD6G', 'get_ServiceLocator_2muTD6GService', true],
            'App\\Controller\\ProductsController:albumEdit' => ['privates', '.service_locator.EmSfoSR', 'get_ServiceLocator_EmSfoSRService', true],
            'App\\Controller\\ProductsController:shirtEdit' => ['privates', '.service_locator.2muTD6G', 'get_ServiceLocator_2muTD6GService', true],
            'App\\Controller\\ProductsController:showOneAlbum' => ['privates', '.service_locator.EmSfoSR', 'get_ServiceLocator_EmSfoSRService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.4u5os03', 'get_ServiceLocator_4u5os03Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\ProductsController::ShowOneShirt' => '?',
            'App\\Controller\\ProductsController::albumEdit' => '?',
            'App\\Controller\\ProductsController::shirtEdit' => '?',
            'App\\Controller\\ProductsController::showOneAlbum' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProductsController:ShowOneShirt' => '?',
            'App\\Controller\\ProductsController:albumEdit' => '?',
            'App\\Controller\\ProductsController:shirtEdit' => '?',
            'App\\Controller\\ProductsController:showOneAlbum' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
