<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVNLinrM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVNLinrM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVNLinrM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVNLinrM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVNLinrM\App_KernelDevDebugContainer([
    'container.build_hash' => 'VNLinrM',
    'container.build_id' => '410f199e',
    'container.build_time' => 1655995821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVNLinrM');
