<?php

namespace Container1GlXv1P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlbumService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EmSfoSR.App\Entity\Album' shared service.
     *
     * @return \App\Entity\Album
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EmSfoSR": it references class "App\\Entity\\Album" but no such service exists.');
    }
}
