<?php

namespace ContainerOAoRK0x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShirtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2muTD6G.App\Entity\Shirt' shared service.
     *
     * @return \App\Entity\Shirt
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2muTD6G": it references class "App\\Entity\\Shirt" but no such service exists.');
    }
}
