<?php

namespace ContainerIEDZbQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2muTD6GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2muTD6G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2muTD6G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'shirt' => ['privates', '.errored..service_locator.2muTD6G.App\\Entity\\Shirt', NULL, 'Cannot autowire service ".service_locator.2muTD6G": it references class "App\\Entity\\Shirt" but no such service exists.'],
        ], [
            'shirt' => 'App\\Entity\\Shirt',
        ]);
    }
}
