<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVZWcvax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVZWcvax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVZWcvax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVZWcvax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVZWcvax\App_KernelDevDebugContainer([
    'container.build_hash' => 'VZWcvax',
    'container.build_id' => '833908d1',
    'container.build_time' => 1655525675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVZWcvax');
