<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.61b1725c.js',
                '/build/186.836f2058.js',
                '/build/app.dd4da228.js',
            ],
            'css' => [
                '/build/app.b75294ae.css',
            ],
        ],
    ],
],

]];
